### PR TITLE
working on GlotPress integration

### PR DESCRIPTION
**Pull request by Mte90**
The pr is not yet ready for merge, I am working to integrate the wp.org stuff and later also remove the stuff that we don't need.

### CODE REVIEW

**Comment by nylen** [comment]
Let's not use a git submodule for glotpress.  It's going to require some changes to the deploy process, and some extra steps for local development.

**Comment by nylen** [comment]
Also, I think we can add the plugins in a single PR and merge it, then continue development in other PRs.

**Comment by Mte90** [comment]
My idea was to have the minimum to have the portal working so we can setup everything, because this plugins improve the UI/UX of glotpress but also adding new routes.
So when everything will work this can be merged and later there will be the optimization with others pr as well.

**Comment by Mte90** [comment]
We need to add `define('GP_URL_BASE', '/');` in wp-config when #10 is merged.

**Comment by nylen** [comment]
@Mte90 is this ready to be merged, with the `wp-config.php` changes you mentioned above?

I still think we need to get rid of the `git submodule`, because this will break our deploys without some further changes, and it will also make it more difficult for other people to contribute.

I'm happy to do that cleanup myself, just let me know.

**Comment by Mte90** [comment]
No I didn't done that changes on wp-config because there was also the changes of your pr, to avoid conflicts.
FOr the gitsubmodule is not a problem, after have this plugins we need to configure it on the portal but I can do it :-)

**Comment by nylen** [comment]
I'll clean up the conflicts and remaining todo items and merge this shortly.  If not today, then tomorrow.

**Pull request merged**
